return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    preset = "modern",
    win = {
      border = "rounded",
      padding = { 1, 2, 1, 2 }, -- top, right, bottom, left
      title = true,
      title_pos = "center",
      zindex = 1000,
    },
    layout = {
      align = "center",
    },
    icons = {
      breadcrumb = "»",
      separator = "➜",
      group = "+",
    },
    spec = {
      mode = { "n", "v" },
      { "<leader><tab>", group = "Tabs" },
      { "<leader>b", group = "Buffer" },
      { "<leader>c", group = "Code" },
      { "<leader>f", group = "File/Find" },
      { "<leader>g", group = "Git" },
      { "<leader>gh", group = "Hunks" },
      { "<leader>gd", group = "Diff" },
      { "<leader>gx", group = "Conflict" },
      { "<leader>q", group = "Session" },
      { "<leader>s", group = "Search" },
      { "<leader>u", group = "UI" },
      { "<leader>w", group = "Window" },
      { "<leader>x", group = "Diagnostics" },
      { "<leader>a", group = "AI" },
      { "[", group = "Prev" },
      { "]", group = "Next" },
      { "g", group = "Goto" },
      { "gs", group = "Surround" },
      { "z", group = "Fold" },
      { "<leader>ba", "<cmd>:enew<cr>", desc = "New Buffer" },
      { "<leader>bx", "<cmd>:%d<cr>", desc = "Clear Buffer" },
      { "<leader>by", "<cmd>:%y<cr>", desc = "Copy Buffer" },
      { "<leader>y", group = "System Copy" },
      { "<leader>p", group = "System Paste" },
      { "<leader>\\", "<cmd>e #<cr>", desc = "Switch to Other Buffer" },
    },
  },
}
