return {
  "folke/which-key.nvim",
  event = "VeryLazy",
  opts = {
    preset = "modern",
    win = {
      border = "rounded",
      padding = { 1, 2, 1, 2 }, -- top, right, bottom, left
      title = true,
      title_pos = "center",
      zindex = 1000,
    },
    layout = {
      align = "center",
    },
    icons = {
      breadcrumb = "»",
      separator = "➜",
      group = "+",
    },
    spec = {
      mode = { "n", "v" },
      { "<leader><tab>", group = "tabs" },
      { "<leader>b", group = "buffer" },
      { "<leader>c", group = "code" },
      { "<leader>f", group = "file/find" },
      { "<leader>g", group = "git" },
      { "<leader>gh", group = "hunks" },
      { "<leader>q", group = "quit/session" },
      { "<leader>s", group = "search" },
      { "<leader>u", group = "ui" },
      { "<leader>w", group = "windows" },
      { "<leader>x", group = "diagnostics/quickfix" },
      { "[", group = "prev" },
      { "]", group = "next" },
      { "g", group = "goto" },
      { "gs", group = "surround" },
      { "z", group = "fold" },
      { "<leader>ba", "<cmd>:enew<cr>", desc = "New Buffer" },
      { "<leader>bx", "<cmd>:%d<cr>", desc = "Clear Buffer" },
      { "<leader>by", "<cmd>:%y<cr>", desc = "Copy Buffer" },
      { "<leader>\\", "<cmd>e #<cr>", desc = "Switch to Other Buffer" },
    },
  },
}
