vim.opt.spell = true
vim.opt.spelllang = "en"
vim.opt.relativenumber = false
vim.opt.cmdheight = 0
vim.opt.backup = true
vim.opt.backupdir = vim.fn.expand("~/.local/state/nvim/backup")
vim.opt.swapfile = false
vim.opt.undofile = false
vim.g.root_spec = { "cwd" }
