return {
  -- {
  --   "folke/snacks.nvim",
  --   opts = {
  --     picker = {
  --       sources = {
  --         explorer = {
  --           auto_close = true,
  --           jump = { close = true },
  --           layout = {
  --             preset = "vscode",
  --             height = 0.8,
  --           },
  --         },
  --         recent = {
  --           filter = {
  --             paths = false,
  --           },
  --         },
  --       },
  --     },
  --   },
  -- },
}
